import { useMemo, useState } from 'react';
import { NODES } from '../lib/proofInspectorData';

const VALUES = [1, 2, 3, -3];

function NodeLink({ id, onSelect, children, className = '' }) {
  return (
    <button type="button" className={`inline-node-link ${className}`} onClick={() => onSelect(id)}>
      {children}
    </button>
  );
}

function MessMultiple({ n }) {
  const magnitude = Math.abs(n);
  const blocks = useMemo(() => Array.from({ length: magnitude }, (_, index) => index), [magnitude]);
  return (
    <div className={`mess-multiple ${n < 0 ? 'negative' : 'positive'}`}>
      <div className="mess-multiple-header">
        <span>coefficient lattice</span>
        <strong>{n} I(O<sub>d</sub>)</strong>
      </div>
      <div className="mess-vector-row" aria-label={`${magnitude} primitive lattice units`}>
        {blocks.map((index) => (
          <div className="mess-vector-unit" key={index}>
            <i>{n < 0 ? '←' : '→'}</i>
            <code>v</code>
          </div>
        ))}
      </div>
      <p>
        Signed coefficient: <b>{n}</b>. Intrinsic sublattice index: <b>|n| = {magnitude}</b>.
      </p>
    </div>
  );
}

function ClassificationProofBranch({ hostile, onSelect }) {
  const [n, setN] = useState(3);
  const magnitude = Math.abs(n);

  return (
    <section id="classification-branch" className="proof-branch-section classification-proof">
      <header className="proof-section-header">
        <div>
          <span>I · CLASSIFICATION BRANCH</span>
          <h2>Why |n| distinguishes the fibrations</h2>
          <p>Every card below is a shortcut to the corresponding node inspector.</p>
        </div>
        <div className="branch-verdict classification">Mess detects the twist</div>
      </header>

      <div className="classification-definition-grid">
        <NodeLink id="family" onSelect={onSelect} className="definition-card">
          <span>family</span>
          <code>Wₙ = F F^(dⁿ)</code>
          <small>F=(B₀B₁B₂c)²</small>
        </NodeLink>
        <NodeLink id="family" onSelect={onSelect} className="definition-card">
          <span>factor subgroup</span>
          <code>H = ⟨B₀,B₁,B₂,c⟩</code>
          <small>d=(t₄t₃)⁶=tδ</small>
        </NodeLink>
        <NodeLink id="family" onSelect={onSelect} className="definition-card">
          <span>intrinsic subgroup</span>
          <code>Kₙ = ⟨H,dⁿHd⁻ⁿ⟩</code>
          <small>generated by factors of Wₙ</small>
        </NodeLink>
      </div>

      <NodeLink id="subgroup-invariance" onSelect={onSelect} className="implication-strip">
        <span>Hurwitz moves preserve the generated subgroup; global conjugation conjugates it.</span>
        <code>Wₘ ~ Wₙ &nbsp;⇒&nbsp; Kₘ and Kₙ are conjugate</code>
      </NodeLink>

      <div className="classification-two-column">
        <NodeLink id="mess-map" onSelect={onSelect} className="proof-notebook-card mess-detector-card">
          <span className="card-kicker">GENUS-TWO REPLACEMENT FOR JOHNSON</span>
          <h3>Mess abelianization</h3>
          <code>μ : I₂ → ℤ[S]</code>
          <p>S is the set of integral symplectic splittings, and μ(tγ)=e(sγ) for a positive separating twist.</p>
          <div className="why-not-johnson">
            <b>Why not Johnson?</b>
            <span>rank(Λ³H/H)=4−4=0 in genus two.</span>
          </div>
        </NodeLink>

        <NodeLink id="torelli-kernel" onSelect={onSelect} className="proof-notebook-card kernel-card">
          <span className="card-kicker">BASELINE TORELLI SUPPORT</span>
          <h3>Matsumoto subgroup</h3>
          <code>H ∩ I₂ = ⟨⟨c⟩⟩<sub>H</sub></code>
          <code>μ(H ∩ I₂)=ℤ[O<sub>c</sub>]</code>
          <p>Kurosh plus the exact quotient-torus and homology calculations identify the entire baseline kernel.</p>
        </NodeLink>
      </div>

      <div className="key-formula-card">
        <button type="button" className="key-formula-main" onClick={() => onSelect('mess-formula')}>
          <span>KEY FORMULA</span>
          <code>μ(Kₙ ∩ I₂) = ℤ[O<sub>c</sub>] ⊕ n I(O<sub>d</sub>)</code>
        </button>
        <div className="n-selector" aria-label="Choose n in the Mess formula">
          {VALUES.map((value) => (
            <button key={value} className={n === value ? 'active' : ''} onClick={() => setN(value)}>
              n={value}
            </button>
          ))}
        </div>
        <MessMultiple n={n} />
        <div className="formula-derivation">
          <code>μ(dⁿ h d⁻ⁿ h⁻¹) = n(e<sub>s_d</sub> − e<sub>ρ(h)s_d</sub>)</code>
          <span>Each H-conjugate contributes a signed orbit difference; together they generate nI(O<sub>d</sub>).</span>
        </div>
      </div>

      <div className="orbit-certificate">
        <NodeLink id="orbit-separation" onSelect={onSelect} className="orbit-profile-card c-profile">
          <span>baseline support</span>
          <strong>θ(s<sub>c</sub>)</strong>
          <code>{'{0,0}'}</code>
        </NodeLink>
        <div className="orbit-not-equal">
          <b>cannot mix</b>
          <i />
          <span>normalizers preserve L mod 2</span>
        </div>
        <NodeLink id="orbit-separation" onSelect={onSelect} className="orbit-profile-card d-profile">
          <span>power-twist support</span>
          <strong>θ(s<sub>d</sub>)</strong>
          <code>{'{1,1}'}</code>
        </NodeLink>
      </div>

      <NodeLink id="magnitude" onSelect={onSelect} className="magnitude-conclusion">
        <span>I(O<sub>d</sub>) contains a primitive difference</span>
        <code>|m| I(O<sub>d</sub>) = |n| I(O<sub>d</sub>) &nbsp;⇒&nbsp; |m|=|n|</code>
      </NodeLink>

      <div className="sign-symmetry-card">
        <NodeLink id="sign-symmetry" onSelect={onSelect} className="sign-symmetry-flow">
          <span>CONVERSE / SIGN SYMMETRY</span>
          <div>
            <code>F F^(dⁿ)</code><i>global conjugation by d⁻ⁿ</i><code>F^(d⁻ⁿ) F</code><i>equal-product block shuttle</i><code>F F^(d⁻ⁿ)</code>
          </div>
          <strong>Wₙ ~ W₋ₙ</strong>
        </NodeLink>
        <p>The block shuttle is the all-integer argument. Finite 120-move replays are exact checks, not the proof of the general case.</p>
      </div>

      <NodeLink id="classification-result" onSelect={onSelect} className="branch-final-card classification">
        <span>FINAL CLASSIFICATION</span>
        <code>Wₘ ~<sub>H,conj</sub> Wₙ &nbsp;⇔&nbsp; |m|=|n|</code>
        <small>The standard factorization-to-fibration correspondence is an external geometric input.</small>
      </NodeLink>

      {hostile && (
        <div className="branch-hostile-summary">
          <span>HOSTILE AUDIT CHECKPOINT</span>
          <p>
            The fatal possibilities are an incomplete Torelli kernel, a conjugator that mixes O<sub>c</sub> and O<sub>d</sub>, a zero/nonprimitive I(O<sub>d</sub>), or a sign argument valid only in a bounded range. Click the implicated nodes to inspect how each is closed.
          </p>
        </div>
      )}
    </section>
  );
}

export default ClassificationProofBranch;
