export const SOURCES = {
  projectClassification: {
    id: 'projectClassification',
    kind: 'project report',
    author: 'Matsumoto power-twist project',
    title: 'Infinite Matsumoto power twists, §15',
    locator: 'Definitions (15.0), formula (15.1), classification (15.2)',
    url: '/verification/classification-proof-extract.md',
    role: 'Fixes the conventions, subgroup invariant, Mess formula, orbit-separation argument, sign symmetry, and evidence boundary used by this inspector.',
  },
  extensionReport: {
    id: 'extensionReport',
    kind: 'project report',
    author: 'Matsumoto power-twist project',
    title: 'Publication-hardened Matsumoto extension theorem',
    locator: 'Theorems A–C and §§2–9',
    url: '/verification/publication-hardened-extension.md',
    role: 'Contains the geometric extension, exact restriction, gluing calculation, source locks, and explicit machine-versus-human evidence boundary.',
  },
  localLemma: {
    id: 'localLemma',
    kind: 'project lemma',
    author: 'Matsumoto power-twist project',
    title: 'The Matsumoto barbell-extension lemma',
    locator: 'Relative-collar lemma and equation (4)',
    url: '/verification/barbell-extension-lemma.md',
    role: 'Supplies the relative cuff-neighborhood straightening argument that is not literally stated in Niu’s proposition.',
  },
  mess: {
    id: 'mess',
    kind: 'external theorem',
    author: 'Geoffrey Mess',
    title: 'The Torelli groups for genus 2 and 3 surfaces',
    locator: 'Topology 31 (1992), 775–790; genus-two Torelli description',
    url: 'https://doi.org/10.1016/0040-9383(92)90008-6',
    role: 'Provides the genus-two Torelli structure underlying the canonical splitting-indexed abelianization μ.',
  },
  bbm: {
    id: 'bbm',
    kind: 'external reference',
    author: 'Mladen Bestvina, Kai-Uwe Bux, Dan Margalit',
    title: 'The Dimension of the Torelli group',
    locator: 'New proof of Mess’s genus-two Torelli theorem',
    url: 'https://arxiv.org/abs/0709.0287',
    role: 'A modern reference for the precise genus-two Torelli description used in the classification branch.',
  },
  kurosh: {
    id: 'kurosh',
    kind: 'external theorem',
    author: 'A. G. Kurosh',
    title: 'The Theory of Groups, Volume 2',
    locator: '§9.34, subgroups of a free product (Kurosh subgroup theorem)',
    url: 'https://old.maa.org/press/maa-reviews/the-theory-of-groups-volume-2',
    role: 'Constrains the finite-index subgroup K of C₂ * C₂ * C₂ and is used to obtain the free rank-three factor.',
  },
  hamada: {
    id: 'hamada',
    kind: 'source data',
    author: 'Noriyuki Hamada',
    title: 'Sections of the Matsumoto–Cadavid–Korkmaz Lefschetz fibration',
    locator: 'Type-IIA four-boundary lift and four disjoint (−1)-sections',
    url: 'https://arxiv.org/abs/1610.08458',
    role: 'Supplies the type-IIA factorization and the exceptional sections E₁,…,E₄.',
  },
  baykurHamada: {
    id: 'baykurHamada',
    kind: 'source data',
    author: 'R. İnanç Baykur and Noriyuki Hamada',
    title: 'Lefschetz fibrations with arbitrary signature',
    locator: 'Transported B₀ curve, published disjointness, and mod-two classes',
    url: 'https://arxiv.org/abs/2010.11916',
    role: 'Supplies the transported B₀ pair from which the matching annulus and sphere are reconstructed.',
  },
  baykur: {
    id: 'baykur',
    kind: 'source data',
    author: 'R. İnanç Baykur',
    title: 'Small symplectic Calabi–Yau surfaces and exotic 4-manifolds via genus-3 pencils',
    locator: 'Capping identification for the B-curves',
    url: 'https://arxiv.org/abs/1511.05951',
    role: 'Fixes the capping behavior needed in the partial-versus-full cap audit.',
  },
  baykurKorkmaz: {
    id: 'baykurKorkmaz',
    kind: 'source data',
    author: 'R. İnanç Baykur and Mustafa Korkmaz',
    title: 'Small Lefschetz fibrations and exotic 4-manifolds',
    locator: 'Source Matsumoto words and two-chain relation',
    url: 'https://arxiv.org/abs/1510.00089',
    role: 'Supplies the textual factorization words and the standard two-chain relation used to identify d.',
  },
  korkmaz: {
    id: 'korkmaz',
    kind: 'source data',
    author: 'Mustafa Korkmaz',
    title: 'Noncomplex smooth 4-manifolds with Lefschetz fibrations',
    locator: 'Genus-two Matsumoto factorization conventions',
    url: 'https://arxiv.org/abs/math/0103135',
    role: 'Source for the concrete B₀, B₁, B₂, c words used by the exact braid calculations.',
  },
  niu: {
    id: 'niu',
    kind: 'external theorem',
    author: 'Weizhe Niu',
    title: 'Mapping class groups of 4-manifolds via barbell diffeomorphisms, Budney–Gabai invariants and handle structures',
    locator: 'PhD thesis (2024), §2.1, Definitions 2.1 and 2.5, Proposition 2.6',
    url: 'https://theses.gla.ac.uk/id/eprint/84779',
    role: 'Provides the boundary-fixing thickened-barbell map, its central point-push picture, and its (t,y)-level normal form. It does not by itself state the project’s open-neighborhood polar-collar conclusion.',
  },
  budneyGabaiBalls: {
    id: 'budneyGabaiBalls',
    kind: 'external construction',
    author: 'Ryan Budney and David Gabai',
    title: 'Knotted 3-balls in S⁴',
    locator: '§5 barbell constructions and implantations',
    url: 'https://arxiv.org/abs/1912.09029',
    role: 'Supports the based-ball model, cuff framing, implantation, and inversion under reversal of the oriented bar.',
  },
  budneyGabaiSigns: {
    id: 'budneyGabaiSigns',
    kind: 'external construction',
    author: 'Ryan Budney and David Gabai',
    title: 'On the automorphism groups of hyperbolic manifolds',
    locator: 'Barbell section; boundary-orientation sign convention',
    url: 'https://arxiv.org/abs/2303.05010',
    role: 'Provides an independent orientation check for the one positive outer and two negative inner boundary twists.',
  },
  identityModel: {
    id: 'identityModel',
    kind: 'imported calculation',
    author: 'Matsumoto power-twist project',
    title: 'Identity-sum elliptic branched-cover model',
    locator: 'Total-space audit, §16.3',
    url: '/verification/identity-sum-extract.md',
    role: 'Identifies X₀ as the resolved double cover of T²×S² with the stated branch set, hence as E(1,1).',
  },
};

export const CLASSIFICATION_NODE_IDS = [
  'family',
  'subgroup-invariance',
  'torelli-kernel',
  'mess-map',
  'mess-formula',
  'orbit-separation',
  'magnitude',
  'sign-symmetry',
  'classification-result',
];

export const EXTENSION_NODE_IDS = [
  'type-iia',
  'matching-sphere',
  'cuff-one',
  'cuff-two',
  'two-cuffs',
  'niu-barbell',
  'polar-collars',
  'beta-restriction',
  'b0-extension',
  'phi-extension',
  'gluing',
  'identity-sum',
  'total-space-result',
];

export const NODES = {
  family: {
    id: 'family', branch: 'classification', title: 'Power-twist family', short: 'Wₙ = F F^(dⁿ)', status: 'mixed',
    claim: 'The family is defined by conjugating every factor of the second Matsumoto block by dⁿ; Kₙ is the subgroup generated by all factors of Wₙ.',
    inputs: ['F = (B₀B₁B₂c)²', 'H = ⟨B₀,B₁,B₂,c⟩', 'd = (t₄t₃)⁶ = tδ ∈ I₂', 'Factorwise conjugation F^g = (g fᵢ g⁻¹)ᵢ'],
    equation: 'Wₙ = F F^(dⁿ)\nKₙ = ⟨H, dⁿ H d⁻ⁿ⟩',
    why: 'The first block generates H. The conjugated second block generates dⁿHd⁻ⁿ, so their union generates Kₙ.',
    sources: ['projectClassification', 'korkmaz', 'baykurKorkmaz'],
    machine: ['Concrete mapping-class words and homology matrices are source-locked and exactly evaluated.', 'No new curve identity is inferred from a drawing.'],
    human: ['The standard correspondence from positive factorizations to oriented Lefschetz fibrations is an external geometric input.'],
    audit: { question: 'Wrong conjugation convention or wrong separating curve?', failure: 'Reversing multiplication order, conjugating by d⁻ⁿ instead of dⁿ, or confusing c with d changes the family.', resolution: 'The project fixes rightmost-first action, records both two-chain supports, and evaluates the source words in exact mapping-class representations.' },
  },
  'subgroup-invariance': {
    id: 'subgroup-invariance', branch: 'classification', title: 'Generated subgroup is intrinsic', short: 'equivalence ⇒ Kₘ ∼ Kₙ', status: 'exact',
    claim: 'If Wₘ and Wₙ are related by Hurwitz moves and simultaneous global conjugation, then Kₘ and Kₙ are conjugate subgroups.',
    inputs: ['Elementary Hurwitz moves replace adjacent factors without changing the subgroup they generate.', 'Global conjugation sends every factor subgroup to a conjugate subgroup.'],
    equation: 'Wₘ ~_(H,conj) Wₙ  ⇒  Kₘ = g Kₙ g⁻¹ for some g ∈ Γ₂',
    why: 'A Hurwitz move replaces (a,b) by (aba⁻¹,a), which generates the same subgroup as (a,b). Global conjugation conjugates the whole generated subgroup.',
    sources: ['projectClassification'],
    machine: ['The concrete factor lists and generated homology images are replayed exactly.'],
    human: ['The allowed equivalence relation must be exactly Hurwitz moves plus simultaneous global conjugation.'],
    audit: { question: 'Could an allowed fibration equivalence change the generated subgroup in some other way?', failure: 'If the equivalence relation silently included an additional move not preserving the generated subgroup, this obstruction would not be intrinsic.', resolution: 'The closed-factorization equivalence used by the theorem is explicitly fixed to elementary Hurwitz moves and arbitrary simultaneous global conjugation.' },
  },
  'torelli-kernel': {
    id: 'torelli-kernel', branch: 'classification', title: 'Matsumoto Torelli kernel', short: 'μ(H∩I₂)=ℤ[O_c]', status: 'mixed',
    claim: 'The Torelli part of H is the normal closure of c, and its Mess image is exactly the orbit module ℤ[O_c].',
    inputs: ['J = B₀B₁B₂c', 'H/⟨J⟩ is index four in C₂*C₂*C₂', 'Kurosh subgroup theorem', 'Exact homology image ρ(H)=R'],
    equation: 'H ∩ I₂ = ⟨⟨c⟩⟩_H\nμ(H ∩ I₂) = ℤ[O_c]',
    why: 'Kurosh and Euler-characteristic constraints give a free rank-three factor; explicit lifts split the central extension. Comparing with Γ(2) on the invariant plane identifies the Torelli kernel as the normal closure of c.',
    sources: ['projectClassification', 'kurosh'],
    machine: ['Index, homology matrices, generators, and the splitting of the concrete central extension are exactly checked.'],
    human: ['Kurosh subgroup theorem is invoked as an external algebraic theorem.'],
    audit: { question: 'Could H∩I₂ contain an additional Torelli direction?', failure: 'An extra generator would enlarge the baseline Mess support and invalidate the direct-sum formula.', resolution: 'The quotient-torus index calculation, Kurosh decomposition, generator bound, and explicit homology image pin the kernel down to the normal closure of c.' },
  },
  'mess-map': {
    id: 'mess-map', branch: 'classification', title: 'Genus-two detector', short: 'μ : I₂ → ℤ[S]', status: 'external',
    claim: 'In genus two, the Torelli group has a canonical equivariant abelianization indexed by integral symplectic splittings.',
    inputs: ['I₂ is the genus-two Torelli group.', 'S is the set of integral symplectic splittings of H₁(Σ₂;ℤ).', 'Positive separating twists determine splitting basis vectors.'],
    equation: 'μ : I₂ → ℤ[S]\nμ(tγ) = e_(sγ)\nμ(gxg⁻¹) = ρ(g) μ(x)',
    why: 'Mess’s genus-two description identifies the Torelli group with a free group generated by separating-twist data. The splitting-indexed abelianization is equivariant under Γ₂.',
    sources: ['mess', 'bbm', 'projectClassification'],
    machine: ['No machine computation proves Mess’s theorem. The checker only evaluates its concrete consequences after the theorem is imported.'],
    human: ['Applicability of Mess’s theorem to the stated genus-two Torelli classes.', 'Identification of the splitting attached to each separating curve.'],
    audit: { question: 'Why not use the Johnson homomorphism?', failure: 'The usual Johnson target Λ³H/H has rank zero in genus two and cannot detect these powers.', resolution: 'The proof explicitly switches to Mess’s splitting-indexed abelianization, whose target is nonzero and equivariant.' },
  },
  'mess-formula': {
    id: 'mess-formula', branch: 'classification', title: 'Intrinsic subgroup formula', short: 'ℤ[O_c] ⊕ n I(O_d)', status: 'mixed',
    claim: 'The Mess image of the Torelli part of Kₙ is the direct sum of the baseline c-orbit module and n times the augmentation-zero d-orbit lattice.',
    inputs: ['μ(H∩I₂)=ℤ[O_c]', 'Kₙ∩I₂ is generated by H∩I₂ and H-conjugates of dⁿhd⁻ⁿh⁻¹.', 'Equivariance and additivity of μ.'],
    equation: 'μ(dⁿ h d⁻ⁿ h⁻¹) = n(e_(s_d) − e_(ρ(h)s_d))\nμ(Kₙ ∩ I₂) = ℤ[O_c] ⊕ n I(O_d)',
    why: 'Each commutator contributes n times a difference of two basis vectors in the d-orbit. These differences generate the augmentation-zero lattice I(O_d); the c- and d-supports are later shown not to mix.',
    sources: ['projectClassification', 'mess'],
    machine: ['Coefficient arithmetic for concrete h, orbit data, and divisibility witnesses is exactly checked.', 'The deterministic classification artifact records witnesses for n=1,…,8 and exact matrices.'],
    human: ['The abstract normal-subgroup generation lemma and Mess theorem are imported.', 'The direct-sum interpretation depends on the orbit-separation step.'],
    audit: { question: 'Could the coefficient be n², 2n, or have a hidden offset?', failure: 'A wrong commutator convention or incomplete generator set changes the coefficient lattice.', resolution: 'The formula is derived from equivariance of μ on dⁿhd⁻ⁿh⁻¹, and exact concrete evaluations confirm linear coefficient n with no offset.' },
  },
  'orbit-separation': {
    id: 'orbit-separation', branch: 'classification', title: 'The supports cannot mix', short: 'θ(s_c)≠θ(s_d)', status: 'exact',
    claim: 'Any symplectic normalizer of R preserves a mod-two profile that separates the c-splitting orbit from the d-splitting orbit.',
    inputs: ['The common rational fixed space of R is L⊥.', 'Every normalizer of R preserves L and L mod 2.', 'Splittings carry an unordered intersection-dimension profile.'],
    equation: 'θ(s_c) = {0,0}\nθ(s_d) = {1,1}',
    why: 'The two profiles are different, so no normalizer capable of conjugating Kₘ to Kₙ can exchange O_c with O_d.',
    sources: ['projectClassification'],
    machine: ['Homology matrices, mod-two subspaces, Plücker coordinates, and both profiles are exactly checked.'],
    human: ['Interpretation of the exact matrices as the stated splitting supports.'],
    audit: { question: 'Could a conjugator trade the baseline ℤ[O_c] term against nI(O_d)?', failure: 'If O_c and O_d lay in the same normalizer orbit, the coefficient n would not be intrinsically assigned to the d-support.', resolution: 'Their invariant profiles are {0,0} and {1,1}; a normalizer preserving L mod 2 cannot exchange them.' },
  },
  magnitude: {
    id: 'magnitude', branch: 'classification', title: 'Recover the magnitude', short: '|m|I(O_d)=|n|I(O_d)', status: 'exact',
    claim: 'Conjugacy of Kₘ and Kₙ forces equality of the absolute-value multiples of I(O_d), and therefore |m|=|n|.',
    inputs: ['The intrinsic formula for μ(Kₙ∩I₂).', 'Orbit separation.', 'I(O_d) contains a primitive nonzero difference.'],
    equation: '|m| I(O_d) = |n| I(O_d)\n⇒ |m| = |n|',
    why: 'Multiplication by different nonnegative integers gives different sublattices when the lattice contains a primitive vector.',
    sources: ['projectClassification'],
    machine: ['The checker verifies B₂(s_d)≠s_d and records a primitive orbit difference.', 'Divisibility witnesses are checked exactly.'],
    human: ['Elementary lattice implication from a primitive vector.'],
    audit: { question: 'What if I(O_d)=0 or only contains divisible vectors?', failure: 'Then the sublattices nI(O_d) might not recover |n|.', resolution: 'An exact moved-splitting computation gives a nonzero primitive difference inside I(O_d).' },
  },
  'sign-symmetry': {
    id: 'sign-symmetry', branch: 'classification', title: 'Recover the converse', short: 'Wₙ ~ W₋ₙ', status: 'mixed',
    claim: 'The positive and negative exponents of the same magnitude define equivalent factorizations.',
    inputs: ['Global conjugation by d⁻ⁿ.', 'Both F blocks have the same product.', 'Pure equal-product block shuttle.'],
    equation: 'Wₙ = F F^(dⁿ)\n—conjugate by d⁻ⁿ→ F^(d⁻ⁿ) F\n—block shuttle→ F F^(d⁻ⁿ) = W₋ₙ',
    why: 'Global conjugation reverses which block is twisted; the equal-product Hurwitz shuttle exchanges the two blocks.',
    sources: ['projectClassification'],
    machine: ['A 120-move exact sign-symmetry replay is recorded for each n=1,…,8.', 'The abstract equal-product block shuttle is checked independently and applies to all n.'],
    human: ['The standard interpretation of the Hurwitz/global-conjugation replay as fibration equivalence.'],
    audit: { question: 'Is the converse only a bounded computational observation?', failure: 'Finite replays alone would not prove Wₙ~W₋ₙ for every integer.', resolution: 'The proof uses an abstract equal-product block-shuttle identity valid in any group; finite replays are checks, not the general argument.' },
  },
  'classification-result': {
    id: 'classification-result', branch: 'classification', title: 'Classification theorem', short: 'iff |m|=|n|', status: 'mixed',
    claim: 'The Matsumoto power-twist factorizations are equivalent exactly when their exponents have the same absolute value.',
    inputs: ['Necessity from the Mess subgroup invariant.', 'Sufficiency from sign symmetry and equality when m=n.'],
    equation: 'Wₘ ~_(H,conj) Wₙ  ⇔  |m| = |n|',
    why: 'The left-to-right implication recovers |n| from an intrinsic conjugacy invariant. The right-to-left implication is identity or the all-integer sign-symmetry construction.',
    sources: ['projectClassification', 'mess'],
    machine: ['Source words, matrices, splitting profiles, primitive witnesses, and sign replays are exact checks.'],
    human: ['Mess and Kurosh are external theorems.', 'Factorization equivalence is interpreted as oriented Lefschetz-fibration isomorphism using the standard correspondence.'],
    audit: { question: 'Does this classify the underlying smooth four-manifolds or marked necks?', failure: 'Overreading the invariant would conflate fibration equivalence with ambient diffeomorphism.', resolution: 'The claim is explicitly about generalized Hurwitz/global-conjugation classes of the displayed factorizations. The unmarked total-space statement is a separate branch.' },
  },

  'type-iia': {
    id: 'type-iia', branch: 'extension', title: 'Transported type-IIA pair', short: 'Q ≅ Σ₀⁴', status: 'mixed',
    claim: 'After the Baykur–Hamada transport, B₀,₁, B′₀,₂, δ₁, and δ₂ bound the planar component Q≅Σ₀⁴.',
    inputs: ['Hamada’s type-IIA four-boundary relation.', 'Baykur–Hamada’s transported curve B′₀,₂ and published disjointness.', 'Printed mod-two classes and the capping identifications.'],
    equation: 'B′₀,₂ = tC₂⁻¹ tB₂,₂⁻¹ tB₁,₂⁻¹(B₀,₂)\n∂Q = B₀,₁ ⊔ B′₀,₂ ⊔ δ₁ ⊔ δ₂',
    why: 'The mod-two class leaves two candidate boundary pairs. Exact partial-versus-full capping excludes {δ₃,δ₄}, selecting {δ₁,δ₂}.',
    sources: ['hamada', 'baykurHamada', 'baykur', 'extensionReport'],
    machine: ['Faithful B₆ comparison after partial and full capping.', 'Boundary-class and support calculations.'],
    human: ['Published disjointness of the transported curves.', 'Geometric interpretation of the selected planar component.'],
    audit: { question: 'Wrong B₀ pair or wrong pair of cap boundaries?', failure: 'Using the raw untransported pair or choosing δ₃,δ₄ changes the matching sphere’s section incidence.', resolution: 'The exact partial-cap non-equality excludes the alternate pair; the full cap equality and printed mod-two classes select δ₁,δ₂.' },
  },
  'matching-sphere': {
    id: 'matching-sphere', branch: 'extension', title: 'Embedded matching sphere', short: 'R=D₁∪B₀D₂', status: 'geometry',
    claim: 'The two Lefschetz thimbles and the capped matching annulus form an embedded sphere R whose halves D₁,D₂ meet E₁,E₂ once respectively and miss the other sections.',
    inputs: ['Disjoint transported vanishing cycles.', 'Disjoint vanishing paths with cyclically adjacent critical values.', 'The two cap centers p₁,p₂ lie in Q.'],
    equation: 'R = D₁ ∪_(B₀) D₂\nR∩E₁={p₁}, R∩E₂={p₂}, R∩E₃=R∩E₄=∅',
    why: 'The annular trace connects the two embedded thimbles. Its only section intersections are the selected cap centers.',
    sources: ['extensionReport', 'hamada', 'baykurHamada'],
    machine: ['Curve support, disjointness data, and the cap-center subset are checked exactly.'],
    human: ['Embeddedness of the thimbles-plus-annulus construction.', 'Choice of disjoint paths and separation of the two section crossings.'],
    audit: { question: 'Could R self-intersect or meet an extra section?', failure: 'A self-intersection or additional section point changes both the framing calculation and the barbell geometry.', resolution: 'Source disjointness and the exact cap audit fix the incidence; the actual embedded matching-sphere construction remains a human differential-topology step.' },
  },
  'cuff-one': {
    id: 'cuff-one', branch: 'extension', title: 'First framing repair', short: 'C₁²=0', status: 'mixed',
    claim: 'Resolving D₁ with E₁ produces a completed disk with the prescribed relative framing zero.',
    inputs: ['e(νD₁,n)=−1', 'E₁²=−1', 'D₁·E₁=+1', 'The intersection is unique and away from the reference fiber.'],
    equation: 'e(νD̂₁,n) = −1 − 1 + 2(+1) = 0',
    why: 'The oriented resolution adds the two normal Euler numbers and twice the positive intersection number.',
    sources: ['extensionReport', 'localLemma'],
    machine: ['Integer arithmetic and the expected exponent bookkeeping.'],
    human: ['D₁ and E₁ are embedded.', 'The unique intersection has positive sign.', 'The local resolution preserves the disk boundary and introduces no extra intersections.'],
    audit: { question: 'Wrong sign or an unrecorded intersection?', failure: 'A negative intersection gives −4 rather than 0; an extra point changes the normal Euler number.', resolution: 'The section is oriented so D₁·E₁=+1, and the cap audit plus separated annular parameters gives exactly one crossing.' },
  },
  'cuff-two': {
    id: 'cuff-two', branch: 'extension', title: 'Second framing repair', short: 'C₂²=0', status: 'mixed',
    claim: 'Resolving D₂ with E₂ independently produces the second completed disk with the prescribed relative framing zero.',
    inputs: ['e(νD₂,n)=−1', 'E₂²=−1', 'D₂·E₂=+1', 'The two resolutions occur in disjoint four-balls.'],
    equation: 'e(νD̂₂,n) = −1 − 1 + 2(+1) = 0',
    why: 'The same signed resolution calculation applies to the second hemisphere without altering the first.',
    sources: ['extensionReport', 'localLemma'],
    machine: ['Integer arithmetic and independent whole-sphere cross-check −2−1−1+2+2=0.'],
    human: ['Disjoint local resolution balls.', 'No genus is introduced: an interior connected sum of a disk and sphere is still a disk.'],
    audit: { question: 'Could the second resolution disturb the first cuff or the fiber?', failure: 'Interacting resolution neighborhoods could destroy disjointness or the common B₀ boundary.', resolution: 'The section crossings are placed at distinct annular parameters and resolved in disjoint four-balls away from Σ.' },
  },
  'two-cuffs': {
    id: 'two-cuffs', branch: 'extension', title: 'Two framed square-zero cuffs', short: 'S₊²=S₋²=0', status: 'geometry',
    claim: 'The relative-zero completed hemispheres glue to a square-zero sphere; opposite push-offs give disjoint framed cuffs S₊ and S₋ meeting Σ cleanly in B₀⁺ and B₀⁻.',
    inputs: ['Both prescribed relative Euler numbers vanish.', 'The common boundary normal n extends over both completed hemispheres.', 'i(B₀,δ)=0.'],
    equation: 'R̂² = −2−1−1+2+2 = 0\n∂P = δ ⊔ B₀⁺ ⊔ B₀⁻',
    why: 'Relative zero—not merely even parity—provides compatible push-off framings. Cutting the one-holed torus along B₀ produces the active pair of pants P.',
    sources: ['extensionReport', 'localLemma'],
    machine: ['Whole-sphere integer cross-check and exact quotient verification i(B₀,δ)=0.'],
    human: ['Gluing completed disks to an embedded sphere.', 'Taking disjoint opposite push-offs with the prescribed framing.', 'Identifying the active central slice with P.'],
    audit: { question: 'Does total square zero really give the needed cuff framing?', failure: 'A square-zero sum could hide opposite relative framing defects on its two hemispheres.', resolution: 'The proof computes each hemisphere’s prescribed relative Euler number separately as zero, so the boundary normal extends over each side.' },
  },
  'niu-barbell': {
    id: 'niu-barbell', branch: 'extension', title: 'Niu barbell input', short: 'outer +, inner −, inner −', status: 'external',
    claim: 'The standard thickened-barbell map has central pair-of-pants restriction equal to one positive outer boundary twist and two negative inner boundary twists.',
    inputs: ['Two disjoint square-zero cuffs.', 'A framed embedded bar joining them.', 'A central twice-punctured-disk/pair-of-pants slice.', 'Boundary-relative barbell model.'],
    equation: '[β|P₀] = t_(a₀) t_(a₊)⁻¹ t_(a₋)⁻¹',
    why: 'Niu’s central point-push model supplies the three boundary twists; boundary orientations determine their signs.',
    sources: ['niu', 'budneyGabaiBalls', 'budneyGabaiSigns', 'extensionReport'],
    machine: ['The project checks the mapped boundary labels and exponent vector after implantation.'],
    human: ['Applicability of the local barbell model to the constructed cuffs and framed bar.', 'Orientation matching between the model and Matsumoto pair.'],
    audit: { question: 'Does Niu’s proposition actually give every relative collar property used here?', failure: 'Treating “twists become trivial toward the ends” as pointwise identity on prescribed open polar collars leaves a gap.', resolution: 'The proof imports only Niu’s stated level model and proves the stronger open-neighborhood conclusion separately via the relative-collar lemma.' },
  },
  'polar-collars': {
    id: 'polar-collars', branch: 'extension', title: 'Relative polar-collar straightening', short: 'fixed pointwise, not setwise', status: 'geometry',
    claim: 'The barbell representative can be made literally the identity on smaller open cuff neighborhoods containing the four off-equatorial polar disks.',
    inputs: ['The based-ball time-one map fixes both cuff spheres pointwise.', 'Its normal derivative along a cuff is a map S²→GL⁺(2,ℝ).', 'Boundary twist annuli can be kept outside still smaller collars.'],
    equation: 'S² → GL⁺(2,ℝ) ≃ S¹\nπ₂(S¹)=0\n⇒ normal derivative is null-homotopic',
    why: 'Relative tubular-neighborhood straightening realizes the null-homotopy as an isotopy to the identity on a smaller cuff neighborhood. The four polar disks are placed inside those neighborhoods.',
    sources: ['localLemma', 'budneyGabaiBalls', 'niu'],
    machine: ['No machine checker proves this differential-topology argument.'],
    human: ['Based-ball isotopy extension.', 'Null-homotopy of the normal derivative.', 'Relative tubular-neighborhood theorem.', 'Support separation between active twist annuli and inactive disks.'],
    audit: { question: 'Are the polar disks only preserved setwise?', failure: 'Setwise preservation could contribute a hidden local twist or nontrivial normal action.', resolution: 'The representative is straightened to the literal identity on open four-dimensional neighborhoods of the disks; this is stronger than setwise preservation.' },
  },
  'beta-restriction': {
    id: 'beta-restriction', branch: 'extension', title: 'Exact surface action', short: 'β|Σ=tδ tB₀⁻²', status: 'mixed',
    claim: 'After implantation, the active pair-of-pants boundaries are exactly δ, B₀⁺, and B₀⁻, so β restricts to tδ tB₀⁺⁻¹ tB₀⁻⁻¹ = tδ tB₀⁻².',
    inputs: ['a₀=δ, a₊=B₀⁺, a₋=B₀⁻.', 'Both inner curves are isotopic to B₀ in the closed fiber.', 'Inactive polar disks are fixed on open neighborhoods.'],
    equation: 'βY|Σ = tδ t_(B₀⁺)⁻¹ t_(B₀⁻)⁻¹ = tδ tB₀⁻²',
    why: 'Only the three active boundary annuli contribute mapping classes; the extra disk components contribute nothing.',
    sources: ['extensionReport', 'localLemma', 'niu'],
    machine: ['Exact sphere-braid coordinates identify the outer support with δ=∂N(c₃∪c₄).', 'Integer audit verifies exponent vector (1,−1,−1).'],
    human: ['Correct implantation of the model barbell into Y.', 'Pointwise-fixed inactive components and orientation of the bar.'],
    audit: { question: 'Could β give d², a conjugate of d, or an extra hidden twist?', failure: 'Any wrong outer support or exponent invalidates the extension theorem.', resolution: 'The mapped outer boundary is independently identified with δ, its exponent is exactly +1, and all non-active components are fixed on open neighborhoods.' },
  },
  'b0-extension': {
    id: 'b0-extension', branch: 'extension', title: 'Product-framed B₀ extension', short: 'MB₀|Σ=tB₀', status: 'geometry',
    claim: 'Local monodromy around the B₀ critical value extends to an ambient diffeomorphism whose germ near Σ is the product of tB₀ with the identity normal map.',
    inputs: ['Parallel transport around the B₀ critical value.', 'An oriented normal two-plane bundle over the based loop.', 'Relative isotopy extension.'],
    equation: 'MB₀(x,z) = (tB₀(x), z) near Σ',
    why: 'Every oriented two-plane bundle over S¹ is trivial, so the normal trivialization can be chosen to close along the loop.',
    sources: ['extensionReport', 'localLemma'],
    machine: ['Exact quotient coordinates verify B₀ is disjoint from δ, so the surface twists commute.'],
    human: ['Choice of closing normal trivialization.', 'Relative isotopy extension with the required product germ.'],
    audit: { question: 'Could the ambient B₀ extension carry an unnoticed normal rotation?', failure: 'A non-product germ would break the boundary gluing identity even if the fiber restriction were correct.', resolution: 'The oriented normal planes over S¹ are trivialized explicitly and closed before applying relative isotopy extension.' },
  },
  'phi-extension': {
    id: 'phi-extension', branch: 'extension', title: 'Cancel the inner twists', short: 'Φ|Σ=d', status: 'mixed',
    claim: 'Composing βY with two product-framed B₀ monodromy extensions cancels the inner boundary twists and leaves exactly d=tδ.',
    inputs: ['βY|Σ=tδtB₀⁻².', 'MB₀|Σ=tB₀.', 'B₀∩δ=∅, hence the twists commute.'],
    equation: 'Φ = MB₀² ∘ βY\nΦ|Σ = tB₀² tδ tB₀⁻² = tδ = d',
    why: 'The two positive B₀ twists cancel the two negative B₀ twists, and disjointness permits the displayed rearrangement.',
    sources: ['extensionReport', 'localLemma'],
    machine: ['Exponent arithmetic (1,−1,−1)+(0,1,1)=(1,0,0).', 'Exact support check B₀∩δ=∅.'],
    human: ['Composition of the ambient pair diffeomorphisms with compatible product germs.'],
    audit: { question: 'Does the cancellation occur only in the mapping class group, or also with the required boundary germ?', failure: 'A fiberwise equality without product normal control would not imply the fiber-sum gluing identity.', resolution: 'Both βY and MB₀ are straightened to product-framed germs, so Φ has germ (x,z)↦(d(x),z).' },
  },
  gluing: {
    id: 'gluing', branch: 'extension', title: 'Boundary gluing identity', short: 'g₀∘Φ̂ⁿ=gₙ', status: 'mixed',
    claim: 'For every positive or negative integer n, applying Φⁿ on one exterior converts the dⁿ-twisted boundary identification into the identity gluing.',
    inputs: ['gₙ(x,e^{iθ})=(dⁿ(x),e⁻ⁱθ).', 'Φ̂(x,e^{iθ})=(d(x),e^{iθ}).', 'Φ is orientation preserving and product-framed near Σ.'],
    equation: 'g₀ ∘ Φ̂ⁿ(x,e^{iθ}) = (dⁿ(x),e⁻ⁱθ) = gₙ(x,e^{iθ})',
    why: 'The piecewise map Φⁿ⊔id respects the quotient equivalence relation defining the fiber sum and descends to Ψₙ:Xₙ→X₀.',
    sources: ['extensionReport'],
    machine: ['Boundary composition bookkeeping for all integer exponents.', 'Normal-circle sign is recorded explicitly.'],
    human: ['Boundary orientation convention for the fiber sum.', 'Smooth descent of the piecewise map to the quotient.'],
    audit: { question: 'Wrong normal-circle sign or boundary germ?', failure: 'Using e^{+iθ} in gₙ or allowing a normal rotation in Φ̂ prevents the two piecewise maps from matching.', resolution: 'The formulas retain the orientation-reversing normal circle in gₙ and the identity normal action in Φ̂; their composition is checked literally.' },
  },
  'identity-sum': {
    id: 'identity-sum', branch: 'extension', title: 'Identify X₀', short: 'X₀≅E(1,1)', status: 'external',
    claim: 'The identity-glued double X₀ is the standard elliptic surface E(1,1).',
    inputs: ['The source branched-cover model M(1,1)→T²×S².', 'In the identity double, deck actions patch.', 'The resolved quotient has four horizontal tori and two vertical spheres in the branch set.'],
    equation: 'X₀ ≅⁺ E(1,1) = E(1)#_(T²)(T²×T²)',
    why: 'Projection to T² gives an elliptic fibration with two I₀* fibers, identifying the resolved double cover with the relatively minimal elliptic surface of holomorphic Euler characteristic one and no multiple fibers.',
    sources: ['identityModel', 'extensionReport'],
    machine: ['The inspector imports this source-locked calculation; it is not re-derived by the barbell checker.'],
    human: ['Branched-cover reconstruction and elliptic-fibration identification.'],
    audit: { question: 'Is E(1,1) being inferred merely from ordinary invariants?', failure: 'Euler characteristic, signature, and π₁ alone would not establish a diffeomorphism type.', resolution: 'The proof imports a specific branched-cover model and elliptic-fibration identification, not a numerical-invariant guess.' },
  },
  'total-space-result': {
    id: 'total-space-result', branch: 'extension', title: 'Fixed smooth total space', short: 'Xₙ≅⁺E(1,1)', status: 'mixed',
    claim: 'Every unmarked total space in the power-twist family is orientation-preservingly diffeomorphic to E(1,1).',
    inputs: ['Ψₙ:Xₙ→X₀ from the boundary gluing identity.', 'The imported identification X₀≅⁺E(1,1).'],
    equation: 'Xₙ ≅⁺ X₀ ≅⁺ E(1,1) for every n∈ℤ',
    why: 'The extending power is absorbed into one summand, reducing every gluing to the identity gluing.',
    sources: ['extensionReport', 'identityModel'],
    machine: ['Exact exponent and gluing-map bookkeeping.'],
    human: ['Existence of the ambient extension Φ and the imported branched-cover identification.'],
    audit: { question: 'Does the diffeomorphism preserve the displayed fibration, sections, neck, or surgery torus?', failure: 'Claiming preservation would be a substantially stronger marked theorem.', resolution: 'The result is explicitly unmarked. No preservation of the displayed fibration, sections, fiber-sum neck, gluing coordinates, or surgery torus is asserted.' },
  },
};

export const ARTIFACTS = [
  {
    label: 'Open verification artifact',
    title: 'Exact B₆ sign-symmetry witness',
    href: '/verification/sign-symmetry-witness.json',
    note: 'A deterministic short replay supporting one concrete sign-symmetry check. It is not the complete classification certificate.',
  },
  {
    label: 'Proof report',
    title: 'Publication-hardened extension report',
    href: '/verification/publication-hardened-extension.md',
    note: 'Full extension argument, source locks, and evidence boundary.',
  },
  {
    label: 'Local lemma',
    title: 'Matsumoto barbell-extension lemma',
    href: '/verification/barbell-extension-lemma.md',
    note: 'Standalone relative-collar and extension argument.',
  },
  {
    label: 'Figure source',
    title: 'Barbell-extension TikZ source',
    href: '/verification/matsumoto_barbell_extension.tex',
    note: 'Exact source supplied with the proof materials.',
  },
  {
    label: 'GitHub',
    title: 'Visualization source branch',
    href: 'https://github.com/seanyang0813/flash-timer/tree/matsumoto-motion',
    note: 'Next.js proof inspector and visualization code.',
  },
];

export const STATUS_META = {
  exact: { label: 'exact computation', tone: 'green' },
  external: { label: 'external theorem', tone: 'violet' },
  geometry: { label: 'human geometry', tone: 'amber' },
  mixed: { label: 'mixed evidence', tone: 'blue' },
  assumption: { label: 'geometric assumption', tone: 'gray' },
};
